### ISSUE TITLE
en_US.UTF-8 UTF-8 isn't installed and causes error in log 

### ISSUE THREAD

**Issue by richardschwabe** [CM2Walki/Squad#11]
When starting the server the first log line is:

```
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
```

The error goes away after manually performing the following steps:

```
1) login as root
2) apt-get update
3) apt-get install locales
4) run dpkg-reconfigure locales
5) choose / type: 158 -> should be en_US.UTF-8 UTF-8
6) set it as default (3)
8) done
```

So it would be great to have the locales installed and set to UTF-8 by default.

**Comment by CM2Walki** [comment]
Is this causing any problems or is it just a warning?

**Comment by richardschwabe** [comment]
Thank you for the quick reply. 

The SquadGame.log, the main log file of a squad server, holds utf-8 encoded string, which look like this without the utf-8 setting:
```
[2021.02.28-18.02.34:832][446]LogEasyAntiCheatServer: [18:02:34][Linux][EAC Server] [Info][RegisterClient] Client: 0x7fc1a4XXXXX PlayerGUID: 7656119XXXXXXX PlayerIP: 7656119XXXXXXX OwnerGUID: 7656119XXXXXXX  PlayerName: ?????????? ????????
```

I stripped certain information with X, however the PlayerName isn't ```?????```, those are usually special characters or Russian or other alphabets. 

Other occuerances with UTF-8 in the log file can also be seen with Admin Broadcasts:

```
[2021.02.28-18.10.08:444][ 37]LogSquad: ADMIN COMMAND: Message broadcasted <switch then live> from ꠞ翁
```

**Comment by CM2Walki** [comment]
I remember seeing this warning in other games as well, it might be a good change for the base image https://github.com/CM2Walki/steamcmd.

**Comment by CM2Walki** [comment]
Alright, change is in the Squad image. Can you give it a try and see if the warning is still there?

**Comment by CM2Walki** [comment]
@richardschwabe could you recheck this, please? So I can close the issue :)
