### ISSUE TITLE
Failed to install app '403240'

### ISSUE THREAD

**Issue by sreitbauer** [CM2Walki/Squad#12]
I'm trying to get a Squad Server running using Docker (Host Windows 10 x64). However, when I start the container it fails with the messages 
```
ERROR! Failed to install app '403240' (Requires 64bit operating system)
sed: can't read /home/steam/squad-dedicated/SquadGame/ServerConfig/Rcon.cfg: No such file or directory
bash: /home/steam/squad-dedicated/SquadGameServer.sh: No such file or directory
```
.

Here's the entire log:

```
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'

[ 0%] Checking for available updates...
[----] Verifying installation...
[ 0%] Downloading update...
[ 0%] Checking for available updates...
[----] Download complete.
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Cleaning up...
[----] Update complete, launching Steamcmd...

Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'

[ 0%] Checking for available updates...
[----] Verifying installation...

Steam Console Client (c) Valve Corporation

-- type 'quit' to exit --

Loading Steam API...OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
ERROR! Failed to install app '403240' (Requires 64bit operating system)
sed: can't read /home/steam/squad-dedicated/SquadGame/ServerConfig/Rcon.cfg: No such file or directory
bash: /home/steam/squad-dedicated/SquadGameServer.sh: No such file or directory
```

I'm not really experienced in Docker, but it might be that the base-image [steamcmd](https://github.com/CM2Walki/steamcmd/blob/master/buster-root/Dockerfile) isn't using the right version of Debian

**Comment by CM2Walki** [comment]
Just tried to replicate on my linux machine and the image still works as expected. Unfortunately, I don't have much experience with Docker for Windows, but the `(Requires 64bit operating system)` quiet a good place to start. 
Could you paste your `docker run` command? 
Also are you using Linux Containers in Docker for Windows?

**Comment by sreitbauer** [comment]
I'm following the [official Squad guide](https://squad.gamepedia.com/Server_Installation). The command I ran is `docker run -d --net=host --name=squad-dedicated cm2network/squad`. I also tried it using WSL, which did not work either.
