### ISSUE TITLE
Steam CMD Disk Write Failure workaround

### ISSUE THREAD

**Issue by immervoll** [CM2Walki/Squad#14]
Issue: When creating the container fresh from the image, steamcmd fails to install the game, due to the current disk write failure.
Solution: Pre create the "steamapps" folder for steamcmd to use.

Further information: https://squad.fandom.com/wiki/Disk_Write_Failure

**Comment by CM2Walki** [comment]
Issue tracked down to a faulty named volume setup. This occurs if steamcmd (executed inside the container by user "steam") tries to write to a directory that wasn't created in the dockerfile, which will be owned by root and result in a disk write failure.
