### ISSUE TITLE
Failed to Start Server with Windows docker

### ISSUE THREAD

**Issue by 0400H** [CM2Walki/Squad#19]
```
docker run -d ^
    --net=host ^
    -e PORT=7787 ^
    -e QUERYPORT=27165 ^
    -e RCONPORT=21114 ^
    -e FIXEDMAXPLAYERS=10 ^
    -e FIXEDMAXTICKRATE=20 ^
    -v "D:\ProgramData\steam\squad\server":/home/steam/squad-dedicated ^
    --name="squad-dedicated-server" ^
    %image%
```
![2021-12-25 084326](https://user-images.githubusercontent.com/16373603/147375056-737ea6a4-b7ed-45ae-8e06-878208c7d1a5.jpg)
[SquadGame.log](https://github.com/CM2Walki/Squad/files/7775302/SquadGame.log)

**Comment by CM2Walki** [comment]
`--net=host` does not work with Docker for Windows, use `-p 7788/tcp -p 7788/udp -p 27166/tcp -p 27166/udp -p 21115/tcp -p 21115/udp` instead
