### ISSUE TITLE
why,and how fixes it?

### ISSUE THREAD

**Issue by milobluebell** [CM2Walki/Squad#24]
hi buddy, i have ran:

> sudo docker run -d --net=host -v /squad-data:/home/steam/squad-dedicated -e PORT=7787 -e QUERYPORT=27166 -e RCONPORT=21115 --name=squad cm2network/squad

and i'm sure /squad-data directory was created, and modified its accessbility to 777

- - -

`BUT, i got`:

![image](https://user-images.githubusercontent.com/11535146/187255115-3ea86098-4d0c-4d74-ae78-96f4f2b0375b.png)

```shell
Success! App '403240' fully installed.
sed: can't read /home/steam/squad-dedicated/SquadGame/ServerConfig/Rcon.cfg: No such file or directory
Clearing Mods...
find: '/home/steam/squad-dedicated/SquadGame/Plugins/Mods/*': No such file or directory
bash: /home/steam/squad-dedicated/SquadGameServer.sh: No such file or directory
```

**Comment by milobluebell** [comment]
@TheDelta  ty

**Comment by milobluebell** [comment]
@CM2Walki  ty

**Comment by TheDelta** [comment]
I just ran your command and it worked w/o/ any issues.
Does /squad-data exist on your system and does /squad-data/SquadGame/ServerConfig/Rcon.cfg exist?

**Comment by milobluebell** [comment]
@TheDelta yup! they exist.    BUT `SquadGameServer.sh` isn', shall i edit this file??

**Comment by milobluebell** [comment]
![7ad250448233831811e5abd21e5a009](https://user-images.githubusercontent.com/11535146/187497450-4a71449b-d981-44c5-bb92-91a17d9037d5.png)

**Comment by TheDelta** [comment]
Remove squad-data and try again.
squad-data should contain:

```server@user /opt/squad-data # ls
Engine   Manifest_DebugFiles_Linux.txt   SquadGame           steamapps
linux64  Manifest_NonUFSFiles_Linux.txt  SquadGameServer.sh  steamclient.so
```

**Comment by milobluebell** [comment]
sry. you mean that, i delete current squad-data dir,and make a new empty dir located at  `$(pwd)/squad-data`.  then , i run docker commands `docker run xxx -v $(pwd)/squad-data:xxxx`, these files you mentions above will be automatically installed to the new dir.

is that right?

**Comment by TheDelta** [comment]
I don't want to turn an issue into a support ticket now.
Simply start completely fresh. A clean run should probably solve this.
(the command you used worked for me w/o/ any issues)

I'm also not sure why you use `docker run`, when you also have a docker-compose.yml ??

**Comment by milobluebell** [comment]
k, i solve the original problem.and got this error logs:

![image](https://user-images.githubusercontent.com/11535146/187586609-cb9ba12c-bc2e-4d52-baf1-d64e368b8e4b.png)

**Comment by TheDelta** [comment]
These have nothing to do with this image / repository and are normal SQUAD errors.
That's something for the SQUAD devs.

This can be /closed now probably

**Comment by milobluebell** [comment]
k, ty
