### ISSUE TITLE
Issues with latest image

### ISSUE THREAD

**Issue by rosarch** [CM2Walki/Squad#3]
I am having some problems with the latest image.

I have downloaded and built from previous builds without issue before, I last updated following the commit on May the 1st.

I decided to update following the release of Squad 14.1 and the addition of MOD support on Linux, I wanted to ensure I had the latest build.

I created a container using the following:
`docker run -d --net=host --volume=/home/rosarch/squad:/home/steam/squad-dedicated --name=squad-dedicated cm2network/squad`

I like having a volume to keep the config stateful.

This is the error from the logs...

```
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
opensslconnection.cpp (1499) : Assertion Failed: unable to load trusted SSL root certificates
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...opensslconnection.cpp (1499) : Assertion Failed: unable to load trusted SSL root certificates
OK.
```

Looking at the logs from another container that is using an older image, it seems to be working ok (even though there is an SteamDatagramTransportLock error), I can connect and play on the server.

```
../steamnetworkingsockets/clientlib/steamnetworkingsockets_lowlevel.cpp (117) : Assertion Failed: SteamDatagramTransportLock held for 32.6ms!
OK.

Connecting anonymously to Steam Public...Logged in OK
```

I know you have made a load of changes recently so can only assume this is why it is no longer working as expected. Any ideas?

**Comment by CM2Walki** [comment]
Hey thanks for reporting this issue, it apparently was introduced recently, when I decided to purge ´ca-certificates´ from the package list of the base images (to reduce image size). Just from plainly googling the issue, it seems that this is the issue. I will reintroduce it to the base image.

**Comment by CM2Walki** [comment]
@rosarch 
The build is finished, the log shows no occurrence of the above error anymore!
Can you test it again? Then I can close this issue :)!

**Comment by rosarch** [comment]
Seems to work a treat - thanks for the very quick turnaround :-)
