### ISSUE TITLE
Issues with logging in to game server via settings in admin cfg

### ISSUE THREAD

**Issue by rosarch** [CM2Walki/Squad#7]
Last year I was using this Docker image to run a few personal Squad servers.
I have been away from squad for a bit and have since rebuilt my server, gaming PC and have anew router.
I have setup squad again and built a few servers using this docker image, my issue is I cant seem to logon without a password using steam credentials via my settings in Admins.cfg and I am not 100% sure what is going wrong. I have carried out various checks and my setup appears to be right.

I am using settings for the config files that I had backed up to GitHub.

This could possible be a Squad game issue or another problem my side. Or, maybe an issue with steam and this build?

When I login with a password I can see my steam ID in the logs. When I try and access without a password and my steam ID etc added to Admins.cfg I cant see anything in the logs when I get the error in the  Squad game GUI.

It would be good if someone can confirm that they can build a server with this image and can login to a pass-worded server without a password and via steam credentials from Admins.cfg, at least I will then know that my issue lies somewhere else - thanks

**Comment by CM2Walki** [comment]
Hey @rosarch,

I killed my Squad server some time ago, so I can't really input anything valuable into the discussion. However, I do remember the Admins.cfg working correctly, as I've been using it myself. Maybe there has been some change to the way they are being loaded? I haven't really kept up-to-date with Squad development.

**Comment by rosarch** [comment]
Thanks @CM2Walki I will keep digging and also ask in the Squad hosting discord. I will raise another issue if I find out that something needs changing.

**Comment by rosarch** [comment]
This can be closed, there is an issue but its not an issue with this docker image.
I built another virtual server following the instructions on the wiki and have exactly the same issue. I believe it's an issue with Squad.

This was working before with the same configs and all ports are open etc, there must have been a change in the game itself with one of the latest updates that doesn't allow you to do this anymore.

**Comment by CM2Walki** [comment]
Alright, thanks for investigating @rosarch. Closed.
